# -*- coding: utf-8 -*-
"""Speech Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aUcfE7sehFHMtQ11Di_mZL5qu6m6U1el

Installing Dependencies
"""

!pip install kagglehub librosa tensorflow scikit-learn matplotlib seaborn

"""Importing Libraries"""

import kagglehub
import os
import numpy as np
import librosa
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Dropout, BatchNormalization
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

"""Downloading Dataset"""

path = kagglehub.dataset_download("jesusrequena/mlend-spoken-numerals")
print("Dataset downloaded to:", path)

# Explore the structure
for root, dirs, files in os.walk(path):
    level = root.replace(path, '').count(os.sep)
    indent = ' ' * 2 * level
    print(f'{indent}{os.path.basename(root)}/')
    if level < 2:
        subindent = ' ' * 2 * (level + 1)
        for f in files[:5]:  # show first 5 files per folder
            print(f'{subindent}{f}')

"""Loading Audio Files and Extracting MFCC features"""

import pandas as pd

# Load CSV
csv_path = os.path.join(path, 'MLEndSND_Audio_Attributes.csv')
df = pd.read_csv(csv_path)
audio_folder = os.path.join(path, 'MLEndSND_Public', 'MLEndSND_Public')

# Check what emotions exist
print("Unique emotions:", df['Intonation'].unique())
print("Emotion counts:\n", df['Intonation'].value_counts())

"""Loading and processing audio files"""

EMOTIONS = df['Intonation'].unique().tolist()
print("Using emotions:", EMOTIONS)

MAX_PAD_LEN = 174
N_MFCC = 40

def extract_mfcc(file_path, max_pad_len=MAX_PAD_LEN, n_mfcc=N_MFCC):
    try:
        audio, sr = librosa.load(file_path, sr=22050, duration=3.0)
        mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=n_mfcc)
        if mfcc.shape[1] < max_pad_len:
            pad_width = max_pad_len - mfcc.shape[1]
            mfcc = np.pad(mfcc, pad_width=((0, 0), (0, pad_width)), mode='constant')
        else:
            mfcc = mfcc[:, :max_pad_len]
        return mfcc
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return None

features = []
labels = []
missing = 0

for _, row in df.iterrows():
    fname = f"{int(row['Public filename']):05d}.wav"
    fpath = os.path.join(audio_folder, fname)
    if not os.path.exists(fpath):
        missing += 1
        continue
    mfcc = extract_mfcc(fpath)
    if mfcc is not None:
        features.append(mfcc)
        labels.append(row['Intonation'])

print(f"\nTotal samples loaded: {len(features)}")
print(f"Missing files: {missing}")
print(f"Label distribution:\n", pd.Series(labels).value_counts())

"""Preprocessing and excoding labels"""

X = np.array(features)          # Shape: (samples, 40, 174)
X = X[..., np.newaxis]          # Add channel dim → (samples, 40, 174, 1)
X = X.reshape(X.shape[0], N_MFCC, MAX_PAD_LEN)  # For CNN1D: (samples, time, features)
X = np.transpose(X, (0, 2, 1))  # → (samples, 174, 40)

# Normalize
X = (X - X.mean()) / (X.std() + 1e-8)

# Encode labels
le = LabelEncoder()
y_encoded = le.fit_transform(labels)
y_cat = to_categorical(y_encoded)

print("X shape:", X.shape)
print("y shape:", y_cat.shape)
print("Classes:", le.classes_)

"""Train-Test Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y_cat, test_size=0.2, random_state=42, stratify=y_cat
)

print(f"Train samples: {X_train.shape[0]}")
print(f"Test samples:  {X_test.shape[0]}")

"""Building the CNN and LSTM hybrid model"""

num_classes = len(EMOTIONS)

model = Sequential([
    # CNN Block 1
    Conv1D(64, kernel_size=5, activation='relu', input_shape=(MAX_PAD_LEN, N_MFCC)),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),
    Dropout(0.3),

    # CNN Block 2
    Conv1D(128, kernel_size=5, activation='relu'),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),
    Dropout(0.3),

    # LSTM Block
    LSTM(128, return_sequences=False),
    Dropout(0.4),

    # Output
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

"""Training the model"""

callbacks = [
    EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=1e-6)
]

history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=32,
    callbacks=callbacks
)

"""Evaluating and visualizing results"""

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title('Accuracy Over Epochs')
plt.xlabel('Epoch'); plt.ylabel('Accuracy'); plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Loss Over Epochs')
plt.xlabel('Epoch'); plt.ylabel('Loss'); plt.legend()

plt.tight_layout()
plt.show()

"""Testing Accuracy and classification report"""

loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"\nTest Accuracy: {accuracy * 100:.2f}%")

y_pred = np.argmax(model.predict(X_test), axis=1)
y_true = np.argmax(y_test, axis=1)

print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=le.classes_))

"""Confusion matrix"""

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=le.classes_, yticklabels=le.classes_)
plt.title('Confusion Matrix')
plt.ylabel('True Label'); plt.xlabel('Predicted Label')
plt.tight_layout()
plt.show()

"""Saving the model"""

model.save('ser_model.h5')
print("Model saved as ser_model.h5")

# Optional: download it to your local machine
from google.colab import files
files.download('ser_model.h5')